LEAGUES = {
    'Америка': [
        'Argentina:Superliga',
        'Brazil:Serie A',
        'Brazil:Serie B',
        'Chile:Primera Division',
        'Copa de Brazil',
        'Mexico:Liga MX',
        'Mexico:Primera Division',
        'Paraguay:Primera Division',
        'Peru: Liga 1',
        'Peru:Primera Division',
        'Uruguay:Primera Division',
        'USA:MLS'
    ],
    'Австралия': [
        'Australia:A-League'
    ],
    'Европа': [
        'Austria:OFB Cup',
        'Austria:Tipico Bundesliga',
        'Austria:2. Liga',
        'Belarus:Vysshaya Liga',
        'Belgium:Jupiler League',
        'Bosnia and Herzegovina:Premier League',
        'Bulgaria:Parva Liga',
        'Croatia:1. HNL',
        'Czech Republic:1. Liga',
        'Denmark:Superliga',
        'England:Championship',
        'England:Premier League',
        'Estonia:Meistriliiga',
        'Europe:Champions League',
        'Europe:Europa League',
        'Finland:Veikkausliiga',
        'France:Ligue 1',
        'France:Ligue 2',
        'Germany:2. Bundesliga',
        'Germany:Bundesliga',
        'Greece:Super League',
        'Hungary:OTP Bank Liga',
        'Iceland:Pepsideild',
        'Italy:Serie A',
        'Italy:Serie B',
        'Latvia:Optibet Virsliga',
        'Lithuania:A Lyga',
        'Moldova:Divizia Nationala',
        'Netherlands:Eerste Divisie',
        'Netherlands:Eredivisie',
        'Norway:Eliteserien',
        'Poland Ekstraklasa',
        'Portugal:LigaPro',
        'Portugal:Primeira Liga',
        'Romania:Liga 1',
        'Russia:FNL',
        'Russia:Premier League',
        'Scotland:Premiership',
        'Serbia:Super Liga',
        'Slovakia:Fortuna liga',
        'Slovenia:Prva liga',
        'Spain:LaLiga',
        'Spain:LaLiga2',
        'Spain:Copa Federacion',
        'Sweden:Allsvenskan',
        'Switzerland:Super League',
        'Ukraine:Persha Liga',
        'Ukraine:Premier League'
    ],
    'Африка': [
        'Egypt:Premier League'
    ],
    'Азия': [
        'Armenia:Premier League',
        'Azerbaijan:Premier League',
        'China:Super League',
        'Georgia:Erovnuli Liga',
        'Israel:Ligat ha\'Al',
        'Japan:J1 League',
        'Kazakhstan:Premier League',
        'Turkey:Super Lig'
    ]
}