# Generated by Django 3.1.4 on 2020-12-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=150)),
                ('period', models.IntegerField()),
            ],
        ),
    ]
