# Generated by Django 3.1.4 on 2020-12-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loggining', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
