# Generated by Django 3.1.4 on 2020-12-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=25)),
                ('league_name', models.CharField(max_length=150)),
                ('match_name', models.CharField(max_length=150)),
                ('total_score', models.CharField(max_length=10)),
                ('first_half_score', models.CharField(max_length=10)),
                ('coef_p1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coef_x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coef_p2', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='NextMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('league_name', models.CharField(blank=True, max_length=150, null=True)),
                ('match_name', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=25)),
                ('coef_p1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coef_x', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coef_p2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
