# Generated by Django 3.1.4 on 2021-02-01 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldNextMatch',
            fields=[
                ('nextmatch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.nextmatch')),
            ],
            bases=('main.nextmatch',),
        ),
    ]
