# Generated by Django 3.1.4 on 2021-02-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_oldnextmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextmatch',
            name='old',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OldNextMatch',
        ),
    ]
